# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b225eb09a2665f3213ac2e29ac4632852a7216754fc2b392b1097c3cd3c8d683214a78f8bdb68675150d00367bc73a094ba884414b523d2b046a21a78f0ebb75

test:
  secret_key_base: 437e816d20a60099d7e259715fabff6417dbfeb18fed13a956beb3f26a45f2c4d94e1929c55798fb8ec8a431900bf6cc1b400e1d1a91a23565872f2e14a6ccd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
